### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by thyrgle** [mattmassicotte/chime#1]
Trying to access http://chimelang.org/ results in:

<img width="1148" alt="screen shot 2015-10-01 at 12 04 11 am" src="https://cloud.githubusercontent.com/assets/349918/10214758/f79ccf00-67cf-11e5-95cf-9b88cdd51d49.png">

**Comment by mattmassicotte** [comment]
Hey @thyrgle - thanks for the report. I was actually floored to find it - I haven't worked on this project in a long time. It was mostly for learning, and a lot of that learning has gone into a new language project which is way more focused and functional: https://github.com/mattmassicotte/three.

Sorry to disappoint!
